# Generated by Django 4.1.3 on 2023-01-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedway_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='match_date',
            field=models.DateTimeField(),
        ),
    ]
